web: python manage.py migrate && python manage.py seed && gunicorn payoutengine.wsgi --bind 0.0.0.0:$PORT --workers 3
worker: celery -A payoutengine worker --loglevel=info --concurrency=2
beat: celery -A payoutengine beat --loglevel=info
