# Generated by Django 5.0.6 on 2026-04-29 01:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('credit_customer_payment', 'Customer payment'), ('debit_payout_hold', 'Payout hold'), ('credit_payout_reversal', 'Payout reversal')], max_length=40)),
                ('amount_paise', models.BigIntegerField()),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='merchants.merchant')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='payouts.payout')),
            ],
            options={
                'db_table': 'ledger_entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['merchant', '-created_at'], name='ledger_entr_merchan_68130b_idx'), models.Index(fields=['payout'], name='ledger_entr_payout__dfbb9d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(check=models.Q(('amount_paise', 0), _negated=True), name='ledger_entry_amount_not_zero'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('amount_paise__gt', 0), ('kind__startswith', 'credit_')), models.Q(('amount_paise__lt', 0), ('kind__startswith', 'debit_')), _connector='OR'), name='ledger_entry_sign_matches_kind'),
        ),
    ]
